name: Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image, run tests, download report generator
      run: docker build . --file Dockerfile.ci --no-cache -t fantast03/spacebattle
    - name: Generate coverage report
      run: docker run --name=tests fantast03/spacebattle
    - name: Copy badges
      run: docker cp tests:/app/coveragereport/ .
    - name: Delete container
      run: docker rm $(docker stop tests)
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        BRANCH_NAME: ${GITHUB_REF##*/}
